In [1]:
import plotly.express as px

In [2]:
x1=[1,2,3,4,5]
y1=[1,23,89,4,5]
fig=px.line(x=x1,y=y1)
fig.show()

In [3]:
import numpy as np

In [8]:
x_=np.random.randint(1,100,100)
y_=np.random.randint(1,100,100)
fig=px.bar(x=x_,y=y_)
fig.show()

In [6]:
x_ , y_

(array([36, 49, 89, 18, 60, 85, 37, 29, 38, 92, 35, 44, 78, 59, 28, 20, 95,
        98,  4, 51, 88, 88, 35, 18, 62, 97, 22, 71, 68, 28, 85, 93, 43, 82,
        43, 42, 21, 24, 47,  7, 97, 19, 62, 62,  4, 35, 23,  6, 13, 95, 32,
        73, 75, 31,  7, 79, 42, 64, 75, 59, 35, 35, 80, 12, 81, 73, 99, 45,
        22, 87, 61, 14, 40, 89, 89,  6, 94, 89, 63, 38, 24, 32, 23, 80, 84,
        13, 37, 32, 33, 94, 48, 91, 31, 49, 46, 53, 40, 91, 78, 85]),
 array([82, 80,  9, 24, 49, 80, 45, 15, 74, 33, 80, 65, 49, 62, 98,  5,  2,
        76, 36, 28, 90, 98, 10, 70, 76, 16, 76, 27, 96, 22, 85,  4, 28, 29,
        13, 38, 70, 25, 58, 25, 82, 11, 67, 85, 99, 10, 50, 32, 27, 37, 77,
        21, 88, 59, 29, 58, 85, 70, 21, 99,  9, 61, 83,  2, 62, 14, 77, 18,
        21, 56, 37, 73, 44, 42, 30, 35, 87, 28, 61, 85, 69, 53, 60, 81, 91,
        62,  8, 57, 28, 55, 42, 51, 88, 12, 72, 66, 47, 95, 76, 69]))

In [9]:
fig=px.scatter(x_,y_)
fig.show()

In [11]:
dir(px.data)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'carshare',
 'election',
 'election_geojson',
 'experiment',
 'gapminder',
 'iris',
 'medals_long',
 'medals_wide',
 'stocks',
 'tips',
 'wind']

In [12]:
df=px.data.tips()
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [14]:
fig=px.histogram(df,x="tip",nbins=20)
fig.show()

In [15]:
fig=px.histogram(df,x="tip",color="size")
fig.show()

In [16]:
fig=px.histogram(df,x="tip",color="sex")
fig.show()

In [17]:
fig=px.histogram(df,x="total_bill",color="sex")
fig.show()

In [18]:
df1=px.data.iris()
df1

sepal_length  sepal_width  ...    species  species_id
0             5.1          3.5  ...     setosa           1
1             4.9          3.0  ...     setosa           1
2             4.7          3.2  ...     setosa           1
3             4.6          3.1  ...     setosa           1
4             5.0          3.6  ...     setosa           1
..            ...          ...  ...        ...         ...
145           6.7          3.0  ...  virginica           3
146           6.3          2.5  ...  virginica           3
147           6.5          3.0  ...  virginica           3
148           6.2          3.4  ...  virginica           3
149           5.9          3.0  ...  virginica           3

[150 rows x 6 columns]

In [21]:
fig=px.scatter(df1,x="sepal_length",y="sepal_width",color="species",size="species_id")
fig.show()

In [23]:
fig=px.pie(values=x_,names=y_)
fig.update_traces(textposition="inside")
fig.show()

In [24]:
df2=px.data.gapminder()
df2

country continent  year  ...   gdpPercap  iso_alpha  iso_num
0     Afghanistan      Asia  1952  ...  779.445314        AFG        4
1     Afghanistan      Asia  1957  ...  820.853030        AFG        4
2     Afghanistan      Asia  1962  ...  853.100710        AFG        4
3     Afghanistan      Asia  1967  ...  836.197138        AFG        4
4     Afghanistan      Asia  1972  ...  739.981106        AFG        4
...           ...       ...   ...  ...         ...        ...      ...
1699     Zimbabwe    Africa  1987  ...  706.157306        ZWE      716
1700     Zimbabwe    Africa  1992  ...  693.420786        ZWE      716
1701     Zimbabwe    Africa  1997  ...  792.449960        ZWE      716
1702     Zimbabwe    Africa  2002  ...  672.038623        ZWE      716
1703     Zimbabwe    Africa  2007  ...  469.709298        ZWE      716

[1704 rows x 8 columns]

In [25]:
fig=px.pie(df1,values="sepal_width",names="species")
fig.show()

In [26]:
import plotly.graph_objects as go

In [28]:
x=[111,2000,500]
y=["s1","s2","s3"]
fig=go.Figure(data=[go.Pie(labels=y,values=x)])
fig.show()

In [33]:
x=[111,2000,500]
y=["s1","s2","s3"]
fig=go.Figure(data=[go.Pie(labels=y,values=x,hole=0.2)])
fig.show()

In [36]:
x=[111,2000,500]
y=["s1","s2","s3"]
fig=go.Figure(data=[go.Pie(labels=y,values=x,pull=[0.5,0,0])])
fig.show()

In [37]:
fig=go.Figure(go.Sunburst(labels=["a","b","c","d","e","f","g","h","i","j","k","l"],
                          parents=["d","d","a","","d","a","b","b","b","e","e","k"],
                          values=[1,2,3,4,5,6,7,8,9,10,11,12]))
fig.show()

In [38]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [39]:
fig=px.sunburst(df,path=["day","time","sex"],values="total_bill")
fig.show()

In [41]:
fig=px.sunburst(df,path=["sex","day","time"],values="total_bill",color="day")
fig.show()

In [51]:
fig=go.Figure(data=[go.Scatter(x=x_,y=y_,mode="markers")])
fig.update_layout(
    updatemenus=[
                 dict(type="buttons",
                      direction="left",
                      buttons=list([
                                    dict(
                                        args=["type","scatter"],
                                         label="scatter plot",
                                         method="restyle"
                                    ),
                                    dict(
                                        args=["type","bar"],
                                         label="bar plot",
                                         method="restyle"
                                    )
                      ]))
    ]
)
fig.show()

In [57]:
fig=go.Figure(data=[go.Scatter(x=x_,y=y_,mode="markers")])
fig.update_layout(
    updatemenus=[
                 dict(direction="up",
                      buttons=list([
                                    dict(
                                        args=["type","scatter"],
                                         label="scatter plot",
                                         method="restyle"
                                    ),
                                    dict(
                                        args=["type","bar"],
                                         label="bar plot",
                                         method="restyle"
                                    )
                      ]))
    ]
)
fig.show()

In [58]:
df1

sepal_length  sepal_width  ...    species  species_id
0             5.1          3.5  ...     setosa           1
1             4.9          3.0  ...     setosa           1
2             4.7          3.2  ...     setosa           1
3             4.6          3.1  ...     setosa           1
4             5.0          3.6  ...     setosa           1
..            ...          ...  ...        ...         ...
145           6.7          3.0  ...  virginica           3
146           6.3          2.5  ...  virginica           3
147           6.5          3.0  ...  virginica           3
148           6.2          3.4  ...  virginica           3
149           5.9          3.0  ...  virginica           3

[150 rows x 6 columns]

In [62]:
fig=px.line_3d(df1,x="sepal_length",y="petal_length",z="petal_width",color="species")
fig.show()

In [63]:
fig=px.scatter_3d(df1,x="sepal_length",y="petal_length",z="petal_width",color="species")
fig.show()

In [64]:
np.linspace(-30,30,30)

array([-30.        , -27.93103448, -25.86206897, -23.79310345,
       -21.72413793, -19.65517241, -17.5862069 , -15.51724138,
       -13.44827586, -11.37931034,  -9.31034483,  -7.24137931,
        -5.17241379,  -3.10344828,  -1.03448276,   1.03448276,
         3.10344828,   5.17241379,   7.24137931,   9.31034483,
        11.37931034,  13.44827586,  15.51724138,  17.5862069 ,
        19.65517241,  21.72413793,  23.79310345,  25.86206897,
        27.93103448,  30.        ])

In [66]:
np.outer(4,[2,2,2])

array([[8, 8, 8]])

In [75]:
x=np.outer(np.linspace(-1.5,1.5,30),np.ones(30))
y=x.copy().T
z=np.tan(x**2+y**2)

fig=go.Figure(data=[go.Surface(x=x,y=y,z=z)])
fig.show()